apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-02-14 - 13:56:17 +0000
  labels:
    app.kubernetes.io/name: fellowship-not-working
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: fellowship-not-working
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: now